name: AI Content Detector

on:
  issues:
    types: [opened, edited]

jobs:
  detect_ai_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install google-generativeai PyGithub python-dotenv

      - name: Run AI Detection Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python detect_ai.py
