name: AI Content Detector

on:
  issues:
    types: [opened, edited]

jobs:
  detect_ai_content:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # ✅ Ensure the workflow can comment & close issues
      contents: read # ✅ Allow reading repo contents

    steps:
      - name: Debug Secrets (Check if they exist)
        run: |
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then echo "❌ GEMINI_API_KEY is missing"; else echo "✅ GEMINI_API_KEY is set"; fi
          if [ -z "${{ secrets.GIT_TOKEN }}" ]; then echo "❌ GIT_TOKEN is missing"; else echo "✅ GIT_TOKEN is set"; fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install google-generativeai PyGithub python-dotenv

      - name: Run AI Detection Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python detect_ai.py
